Flake8:
    script:
    - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
    - ". ./prepare-and-run-flake8.sh volumential test"
    tags:
    - python3
    except:
    - tags

Python 3 POCL:
  script:
  - export PY_EXE=python3
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="pybind11 numpy pytest scipy mako wheel"
  - git submodule sync && git submodule update --init --recursive --remote
  - ((cd contrib/meshgen11_dealii/; ./build.sh) && echo "Using meshgen11_dealii.") || (echo "Using boxtree for meshgen.")
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - pocl
  - dealii
  except:
  - tags

Documentation Sphinx:
  script:
  - export PY_EXE=python3
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="pybind11 numpy pytest scipy mako wheel"
  - git submodule sync && git submodule update --init --recursive --remote
  - ((cd contrib/meshgen11_dealii/; ./build.sh) && echo "Using meshgen11_dealii.") || (echo "Using boxtree for meshgen.")
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-py-project.sh
  - ". ./build-py-project.sh"
  - cd doc && make html
  - git config --global user.name "${COMMIT_USER}"
  - git config --global user.email "${COMMIT_EMAIL}"
  - git clone https://${GH_USER}:${GH_ACCESS_TOKEN}@${HOMEPAGE_URL} homepage
  - cd homepage
  - git checkout src
  - cd static && mkdir -p docs
  - rm -rf docs/volumential
  - cp -r ../../build/html docs/volumential
  - git add -f ./docs/volumential
  - (git commit -m "Auto-updated volumential docs") || (echo "Docs are up to date")
  - git push
  tags:
  - python3
  - pocl
  - dealii
  except:
  - tags
